name: workflow to download the repo on runner machine
on: [ push ]

jobs:
  checkout-repo-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1. Starting the Job
        run: echo "Starting the Job at $(date)"

      - name: step 2. listing files before downloading our repo
        run: ls -a

      - name: step 3. checking out the repo
        uses: actions/checkout@v4

      - name: step 4. listing files after repo checkout
        run: ls -a

      - name: step 5. Ending the Job
        run: echo "Ended the Job at $(date)"