name: 2D matrix demonstration - running different test suites on different runner machine os types

on:
  workflow_dispatch:


jobs:
  test-execution-via-1D-matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        test-suite-name: [smokeTestSuite.xml, regressionTestSuite.xml, sanityTestSuite.xml]
    runs-on: ${{ matrix.os }}
    steps:
      - name: step 1. Starting the test
        run: echo 'Testing is getting started'

      - name: Step 2 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 3 - Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Step 4 - Run the selected tests
        run: |
          echo "Executing '${{ matrix.test-suite-name }}' tests..."
          mvn clean test -Dsuite=${{ matrix.test-suite-name }}
