name: Manually Triggered Test Runner

on:
  workflow_dispatch:
    inputs:
      userName:
        description: "Enter your name"
        type: string
        required: true
        default: "Ashish Mishra"
      testPriority:
        description: "Test priority (e.g., 1 = P1, 2 = P2)"
        type: number
        default: 2
      testType:
        description: "Select type of test to run"
        type: choice
        required: true
        default: "smoke"
        options:
          - smoke
          - regression
          - sanity
      purpose:
        description: "what's the purpose to run these Test pipeline?"
        type: string
        required: false

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    if: github.ref_name == 'manualTriggerBranch'
    steps:
      - name: Step 1 - Acknowledge Trigger
        run: |
          echo "Hi ${{ inputs.userName }} 👋"
          echo "You triggered this on branch: ${{ github.ref_name }}"
          echo "Test Type: ${{ inputs.testType }}"
          echo "Test Priority: P${{ inputs.testPriority }}"
          echo "Purpose to run: ${{ inputs.purpose }}"

      - name: Step 2 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 3 - Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # or 11 based on your project

      - name: Step 4 - Run the selected tests (if opted in)
        run: |
          echo "Executing '${{ inputs.testType }}' tests..."
          
          if [[ "${{ inputs.testType }}" == "smoke" ]]; then
            mvn clean test -Dsuite=smokeTestSuite.xml
          
          elif [[ "${{ inputs.testType }}" == "regression" ]]; then
            mvn clean test -Dsuite=regressionTestSuite.xml
          
          elif [[ "${{ inputs.testType }}" == "sanity" ]]; then
            mvn clean test -Dsuite=sanityTestSuite.xml


      - name: Step 5 - Test Run Completed
        run: echo "Test Execution completed"

      - name: Step 6 - Wrap Up
        run: echo "✅ Job completed for ${{ inputs.userName }} on branch ${{ github.ref_name }}"