name: Schedule workflow to run regression test

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled-regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 2 - Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Step 3 - Starting the Test
        run: echo "Starting the Test..."

      - name: Step 4 - Running Regression Suite
        run: mvn clean test -Dsuite=regressionTestSuite.xml

      - name: Step 5 - Test Run Completed
        run: echo "Test Execution completed"