name: Environment and repo level variables and secrets

on:
  workflow_dispatch:

jobs:
  job-for-qa-env:
    runs-on: ubuntu-latest
    environment: "qa"
    env:
      DATABASE_CONNECTION_STRING_SECRET: ${{ secrets.DATABASE_CONNECTION_STRING }}
      WEB_URL_ENV_VARIABLE: ${{ vars.WEB_URL }}
      USER_NAME_ENV_VARIABLE: ${{ vars.USER_NAME }}
      REPO_FIRST_VARIABLE_KEY_VARIABLE: ${{ vars.REPO_FIRST_VARIABLE_KEY }}
    steps:
      - name: Step 1 - Printing variables for QA
        run: |
          echo "✅ Environment: ${{ job.environment }}"
          echo "🔹 DataBase connection String value: $DATABASE_CONNECTION_STRING_SECRET"
          echo "🔹 Web Url: $WEB_URL_ENV_VARIABLE"
          echo "🔹 User Name: $USER_NAME_ENV_VARIABLE"
          echo "🔹 Repo first variable value: $REPO_FIRST_VARIABLE_KEY_VARIABLE"

  job-for-dev-env:
    runs-on: ubuntu-latest
    environment: "dev"
    env:
      DATABASE_CONNECTION_STRING_SECRET: ${{ secrets.DATABASE_CONNECTION_STRING }}
      WEB_URL_ENV_VARIABLE: ${{ vars.WEB_URL }}
      USER_NAME_ENV_VARIABLE: ${{ vars.USER_NAME }}
      REPO_FIRST_VARIABLE_KEY_VARIABLE: ${{ vars.REPO_FIRST_VARIABLE_KEY }}
    steps:
      - name: Step 1 - Printing variables for DEV
        run: |
          echo "✅ Environment: ${{ job.environment }}"
          echo "🔹 DataBase connection String value: $DATABASE_CONNECTION_STRING_SECRET"
          echo "🔹 Web Url: $WEB_URL_ENV_VARIABLE"
          echo "🔹 User Name: $USER_NAME_ENV_VARIABLE"
          echo "🔹 Repo first variable value: $REPO_FIRST_VARIABLE_KEY_VARIABLE"

  job-for-prod-env:
    runs-on: ubuntu-latest
    environment: "prod"
    env:
      DATABASE_CONNECTION_STRING_SECRET: ${{ secrets.DATABASE_CONNECTION_STRING }}
      WEB_URL_ENV_VARIABLE: ${{ vars.WEB_URL }}
      USER_NAME_ENV_VARIABLE: ${{ vars.USER_NAME }}
      REPO_FIRST_VARIABLE_KEY_VARIABLE: ${{ vars.REPO_FIRST_VARIABLE_KEY }}
    steps:
      - name: Step 1 - Printing variables for PROD
        run: |
          echo "✅ Environment: ${{ job.environment }}"
          echo "🔹 DataBase connection String value: $DATABASE_CONNECTION_STRING_SECRET"
          echo "🔹 Web Url: $WEB_URL_ENV_VARIABLE"
          echo "🔹 User Name: $USER_NAME_ENV_VARIABLE"
          echo "🔹 Repo first variable value: $REPO_FIRST_VARIABLE_KEY_VARIABLE"
