name: a simple workflow to find java, maven, docker version on runner machine using dependant task
on: [ push ]

jobs:
  initial-setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1. Starting the Job
        run: echo "Starting the Job at $(date)"

      - name: step 2. finding java version
        run: echo "Workflow started"

      - name: step 3. Ending the Job
        run: echo "Ended the Job at $(date)"

  java-version-check-job-1:
    runs-on: ubuntu-latest
    needs: initial-setup-job
    steps:
      - name: step 1. Starting the Job
        run: echo "Starting the Job at $(date)"

      - name: step 2. finding java version
        run: |
          java --version
          echo "JAVA JOB: Sleeping for 20s..."
          sleep 10

      - name: step 3. Ending the Job
        run: echo "Ended the Job at $(date)"

  maven-version-check-job-2:
    runs-on: ubuntu-latest
    needs: java-version-check-job-1
    steps:
      - name: step 1. Starting the Job
        run: echo "Starting the Job at $(date)"

      - name: step 2. finding maven version
        run: |
          mvn --version
          echo "Maven JOB: Sleeping for 10s..."
          sleep 20

      - name: step 3. Ending the Job
        run: echo "Ended the Job at $(date)"

  docker-version-check-job-3:
    runs-on: ubuntu-latest
    needs: maven-version-check-job-2
    steps:
      - name: step 1. Starting the Job
        run: echo "Starting the Job at $(date)"

      - name: step 2. finding docker version
        run: |
          docker --version
          echo "Docker JOB: Sleeping for 10s..."
          sleep 10

      - name: step 3. Ending the Job
        run: echo "Ended the Job at $(date)"