name: Environment and repo level variables and secrets

on:
  workflow_dispatch:

jobs:
  job-for-qa-env:
    runs-on: ubuntu-latest
    environment: "qa"
    env:
      DATABASE_CONNECTION_STRING_SECRET: ${{ secrets.DATABASE_CONNECTION_STRING }}
      WEB_URL_ENV_VARIABLE: {{ vars.WEB_URL }}
      REPO_FIRST_VARIABLE_KEY_VARIABLE: {{ vars.REPO_FIRST_VARIABLE_KEY }}
    steps:
      - name: step 1. Running job for QA environment and printing the values below
        run: |
          echo "🔹 DataBase connection String value: $DATABASE_CONNECTION_STRING_SECRET"
          echo "🔹 Web Url: $WEB_URL_ENV_VARIABLE"
          echo "🔹 Repo first variable value: $REPO_FIRST_VARIABLE_KEY_VARIABLE"

  job-for-dev-env:
    runs-on: ubuntu-latest
    environment: "dev"
    env:
      DATABASE_CONNECTION_STRING_SECRET: ${{ secrets.DATABASE_CONNECTION_STRING }}
      WEB_URL_ENV_VARIABLE: { { vars.WEB_URL } }
      REPO_FIRST_VARIABLE_KEY_VARIABLE: { { vars.REPO_FIRST_VARIABLE_KEY } }
    steps:
      - name: step 1. Running job for dev environment and printing the values below
        run: |
          echo "🔹 DataBase connection String value: $DATABASE_CONNECTION_STRING_SECRET"
          echo "🔹 Web Url: $WEB_URL_ENV_VARIABLE"
          echo "🔹 Repo first variable value: $REPO_FIRST_VARIABLE_KEY_VARIABLE"