name: Expressions and Context

run-name: "Printing Expressions and Context by user: @${{ github.actor }}, event: ${{ github.event_name }}"

on:
  workflow_dispatch:

jobs:
  printing-values:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying some Expressions
        run: |
          echo "1 evaluates to: ${{ 1 }}"
          echo "'this is a String' evaluates to: ${{ 'this is a String' }}"
          echo "null evaluates to: ${{ null }}"
          echo "true evaluates to: ${{ true }}"
          echo "Is 1 > 2? => ${{ 1 > 2 }}"
          echo "Is 'string' == 'String'? => ${{ 'string' == 'String' }}"
          echo "true && false evaluates to: ${{ true && false }}"
          echo "true || false evaluates to: ${{ true || false }}"

      - name: Displaying some Contexts
        run: |
          echo "GitHub Context: ${{ toJson(github) }}"
          echo "Job Context: ${{ toJson(job) }}"
          echo "Secrets Context: ${{ toJson(secrets) }}"
          echo "Steps Context: ${{ toJson(steps) }}"
          echo "Runner Context: ${{ toJson(runner) }}"