name: Artifact for test run

on:
  workflow_dispatch:
    inputs:
      testType:
        description: "Select type of test to run"
        type: choice
        required: true
        default: "smoke"
        options:
          - smoke
          - regression
          - sanity

jobs:
  run-test-cases-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1. Checking out the code
        uses: actions/checkout@v4
      - name: Step 2. Listing files before running test cases
        run: ls
      - name: Step 3 - Run the selected tests
        run: |
          echo "Executing '${{ inputs.testType }}' tests..."

          if [[ "${{ inputs.testType }}" == "smoke" ]]; then
            mvn clean test -Dsuite=smokeTestSuite.xml

          elif [[ "${{ inputs.testType }}" == "regression" ]]; then
            mvn clean test -Dsuite=regressionTestSuite.xml

          elif [[ "${{ inputs.testType }}" == "sanity" ]]; then
            mvn clean test -Dsuite=sanityTestSuite.xml
          fi
      - name: Steps 4. Listing files after running test cases
        run: ls
      - name: Step 5. Uploading the file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-upload-name
          path: target/surefire-reports/

  display-test-report-job:
    needs: run-test-cases-job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1. Listing files before downloading test results
        run: ls
      - name: Step 2. Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports-upload-name
          path: downloaded-reports/
      - name: Steps 3. Listing files after running test cases
        run: find .
      - name: Step 4. display the test results
        run: cat downloaded-reports/*.txt