name: p23_slack_notification

on:
  workflow_dispatch:
    inputs:
      testType:
        description: "Select type of test to run"
        type: choice
        required: true
        default: "smoke"
        options:
          - smoke
          - regression
          - sanity
          - unit_test

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:

      - name:  Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # or 11 based on your project

      - name: Run the selected tests
        run: |
          echo "Executing '${{ inputs.testType }}' tests..."
          
          if [[ "${{ inputs.testType }}" == "smoke" ]]; then
            mvn clean test -Dsuite=smokeTestSuite.xml
          
          elif [[ "${{ inputs.testType }}" == "regression" ]]; then
            mvn clean test -Dsuite=regressionTestSuite.xml
          
          elif [[ "${{ inputs.testType }}" == "sanity" ]]; then
            mvn clean test -Dsuite=sanityTestSuite.xml

          elif [[ "${{ inputs.testType }}" == "unit_test" ]]; then
            mvn clean test -Dsuite=failregressionTestSuite.xml
          
          fi

      - name:  Test Run Completed
        if: always()
        run: echo "Test Execution completed"

      - name: Wrap Up
        if: always()
        run: |
          echo "✅ Job completed for ${{ inputs.userName }} on branch ${{ github.ref_name }}"
          cat target/surefire-reports/TestSuite.txt

      - name: Read TestSuite.txt into summary
        if: always()
        id: test_summary
        run: |
          summary=""
          if [ -f target/surefire-reports/TestSuite.txt ]; then
            summary=$(cat target/surefire-reports/TestSuite.txt)
            summary="${summary//\"/\\\"}"  # escape double quotes
          else
            summary="⚠️ No TestSuite.txt file found."
          fi
          echo "summary=$summary" >> $GITHUB_OUTPUT


      - name: Set Slack Color
        id: slack_color
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "color=#36a64f" >> $GITHUB_OUTPUT
          else
            echo "color=#ff0000" >> $GITHUB_OUTPUT
          fi

      - name: publish test results on Slack
        if: always()
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Test Automation Results
          SLACK_MESSAGE: ${{ steps.test_summary.outputs.summary }}
          SLACK_COLOR: ${{ steps.slack_color.outputs.color }}